/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_alloc_context {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_alloc_context(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_alloc_context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_alloc_context obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_alloc_context(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUser(SWIGTYPE_p_void value) {
    mupdfJNI.fz_alloc_context_user_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUser() {
    long cPtr = mupdfJNI.fz_alloc_context_user_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setMalloc(SWIGTYPE_p_f_p_void_size_t__p_void value) {
    mupdfJNI.fz_alloc_context_malloc_set(swigCPtr, this, SWIGTYPE_p_f_p_void_size_t__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_size_t__p_void getMalloc() {
    long cPtr = mupdfJNI.fz_alloc_context_malloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_size_t__p_void(cPtr, false);
  }

  public void setRealloc(SWIGTYPE_p_f_p_void_p_void_size_t__p_void value) {
    mupdfJNI.fz_alloc_context_realloc_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void_size_t__p_void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void_size_t__p_void getRealloc() {
    long cPtr = mupdfJNI.fz_alloc_context_realloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void_size_t__p_void(cPtr, false);
  }

  public void setFree(SWIGTYPE_p_f_p_void_p_void__void value) {
    mupdfJNI.fz_alloc_context_free_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_void__void getFree() {
    long cPtr = mupdfJNI.fz_alloc_context_free_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_void__void(cPtr, false);
  }

  public fz_alloc_context() {
    this(mupdfJNI.new_fz_alloc_context(), true);
  }

}
