/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_aa_context {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_aa_context(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_aa_context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_aa_context obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_aa_context(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setHscale(int value) {
    mupdfJNI.fz_aa_context_hscale_set(swigCPtr, this, value);
  }

  public int getHscale() {
    return mupdfJNI.fz_aa_context_hscale_get(swigCPtr, this);
  }

  public void setVscale(int value) {
    mupdfJNI.fz_aa_context_vscale_set(swigCPtr, this, value);
  }

  public int getVscale() {
    return mupdfJNI.fz_aa_context_vscale_get(swigCPtr, this);
  }

  public void setScale(int value) {
    mupdfJNI.fz_aa_context_scale_set(swigCPtr, this, value);
  }

  public int getScale() {
    return mupdfJNI.fz_aa_context_scale_get(swigCPtr, this);
  }

  public void setBits(int value) {
    mupdfJNI.fz_aa_context_bits_set(swigCPtr, this, value);
  }

  public int getBits() {
    return mupdfJNI.fz_aa_context_bits_get(swigCPtr, this);
  }

  public void setText_bits(int value) {
    mupdfJNI.fz_aa_context_text_bits_set(swigCPtr, this, value);
  }

  public int getText_bits() {
    return mupdfJNI.fz_aa_context_text_bits_get(swigCPtr, this);
  }

  public void setMin_line_width(float value) {
    mupdfJNI.fz_aa_context_min_line_width_set(swigCPtr, this, value);
  }

  public float getMin_line_width() {
    return mupdfJNI.fz_aa_context_min_line_width_get(swigCPtr, this);
  }

  public fz_aa_context() {
    this(mupdfJNI.new_fz_aa_context(), true);
  }

}
