/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public final class fz_box_type {
  public final static fz_box_type FZ_MEDIA_BOX = new fz_box_type("FZ_MEDIA_BOX");
  public final static fz_box_type FZ_CROP_BOX = new fz_box_type("FZ_CROP_BOX");
  public final static fz_box_type FZ_BLEED_BOX = new fz_box_type("FZ_BLEED_BOX");
  public final static fz_box_type FZ_TRIM_BOX = new fz_box_type("FZ_TRIM_BOX");
  public final static fz_box_type FZ_ART_BOX = new fz_box_type("FZ_ART_BOX");
  public final static fz_box_type FZ_UNKNOWN_BOX = new fz_box_type("FZ_UNKNOWN_BOX");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static fz_box_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + fz_box_type.class + " with value " + swigValue);
  }

  private fz_box_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private fz_box_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private fz_box_type(String swigName, fz_box_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static fz_box_type[] swigValues = { FZ_MEDIA_BOX, FZ_CROP_BOX, FZ_BLEED_BOX, FZ_TRIM_BOX, FZ_ART_BOX, FZ_UNKNOWN_BOX };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

