/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_colorspace {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_colorspace(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_colorspace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_colorspace obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_colorspace(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKey_storable(SWIGTYPE_p_fz_key_storable value) {
    mupdfJNI.fz_colorspace_key_storable_set(swigCPtr, this, SWIGTYPE_p_fz_key_storable.getCPtr(value));
  }

  public SWIGTYPE_p_fz_key_storable getKey_storable() {
    return new SWIGTYPE_p_fz_key_storable(mupdfJNI.fz_colorspace_key_storable_get(swigCPtr, this), true);
  }

  public void setType(fz_colorspace_type value) {
    mupdfJNI.fz_colorspace_type_set(swigCPtr, this, value.swigValue());
  }

  public fz_colorspace_type getType() {
    return fz_colorspace_type.swigToEnum(mupdfJNI.fz_colorspace_type_get(swigCPtr, this));
  }

  public void setFlags(int value) {
    mupdfJNI.fz_colorspace_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return mupdfJNI.fz_colorspace_flags_get(swigCPtr, this);
  }

  public void setN(int value) {
    mupdfJNI.fz_colorspace_n_set(swigCPtr, this, value);
  }

  public int getN() {
    return mupdfJNI.fz_colorspace_n_get(swigCPtr, this);
  }

  public void setName(byte[] value) {
    mupdfJNI.fz_colorspace_name_set(swigCPtr, this, value);
  }

  public byte[] getName() {
    return mupdfJNI.fz_colorspace_name_get(swigCPtr, this);
  }

  public fz_colorspace_u getU() {
    long cPtr = mupdfJNI.fz_colorspace_u_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace_u(cPtr, false);
  }

  public fz_colorspace() {
    this(mupdfJNI.new_fz_colorspace(), true);
  }

}
