/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_context {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_context(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_context obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_context(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUser(SWIGTYPE_p_void value) {
    mupdfJNI.fz_context_user_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUser() {
    long cPtr = mupdfJNI.fz_context_user_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setAlloc(fz_alloc_context value) {
    mupdfJNI.fz_context_alloc_set(swigCPtr, this, fz_alloc_context.getCPtr(value), value);
  }

  public fz_alloc_context getAlloc() {
    long cPtr = mupdfJNI.fz_context_alloc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_alloc_context(cPtr, false);
  }

  public void setLocks(fz_locks_context value) {
    mupdfJNI.fz_context_locks_set(swigCPtr, this, fz_locks_context.getCPtr(value), value);
  }

  public fz_locks_context getLocks() {
    long cPtr = mupdfJNI.fz_context_locks_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_locks_context(cPtr, false);
  }

  public void setError(fz_error_context value) {
    mupdfJNI.fz_context_error_set(swigCPtr, this, fz_error_context.getCPtr(value), value);
  }

  public fz_error_context getError() {
    long cPtr = mupdfJNI.fz_context_error_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_error_context(cPtr, false);
  }

  public void setWarn(fz_warn_context value) {
    mupdfJNI.fz_context_warn_set(swigCPtr, this, fz_warn_context.getCPtr(value), value);
  }

  public fz_warn_context getWarn() {
    long cPtr = mupdfJNI.fz_context_warn_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_warn_context(cPtr, false);
  }

  public void setAa(fz_aa_context value) {
    mupdfJNI.fz_context_aa_set(swigCPtr, this, fz_aa_context.getCPtr(value), value);
  }

  public fz_aa_context getAa() {
    long cPtr = mupdfJNI.fz_context_aa_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_aa_context(cPtr, false);
  }

  public void setSeed48(int[] value) {
    mupdfJNI.fz_context_seed48_set(swigCPtr, this, value);
  }

  public int[] getSeed48() {
    return mupdfJNI.fz_context_seed48_get(swigCPtr, this);
  }

  public void setThrow_on_repair(int value) {
    mupdfJNI.fz_context_throw_on_repair_set(swigCPtr, this, value);
  }

  public int getThrow_on_repair() {
    return mupdfJNI.fz_context_throw_on_repair_get(swigCPtr, this);
  }

  public void setHandler(SWIGTYPE_p_fz_document_handler_context value) {
    mupdfJNI.fz_context_handler_set(swigCPtr, this, SWIGTYPE_p_fz_document_handler_context.getCPtr(value));
  }

  public SWIGTYPE_p_fz_document_handler_context getHandler() {
    long cPtr = mupdfJNI.fz_context_handler_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fz_document_handler_context(cPtr, false);
  }

  public void setArchive(SWIGTYPE_p_fz_archive_handler_context value) {
    mupdfJNI.fz_context_archive_set(swigCPtr, this, SWIGTYPE_p_fz_archive_handler_context.getCPtr(value));
  }

  public SWIGTYPE_p_fz_archive_handler_context getArchive() {
    long cPtr = mupdfJNI.fz_context_archive_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fz_archive_handler_context(cPtr, false);
  }

  public void setStyle(SWIGTYPE_p_fz_style_context value) {
    mupdfJNI.fz_context_style_set(swigCPtr, this, SWIGTYPE_p_fz_style_context.getCPtr(value));
  }

  public SWIGTYPE_p_fz_style_context getStyle() {
    long cPtr = mupdfJNI.fz_context_style_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fz_style_context(cPtr, false);
  }

  public void setTuning(SWIGTYPE_p_fz_tuning_context value) {
    mupdfJNI.fz_context_tuning_set(swigCPtr, this, SWIGTYPE_p_fz_tuning_context.getCPtr(value));
  }

  public SWIGTYPE_p_fz_tuning_context getTuning() {
    long cPtr = mupdfJNI.fz_context_tuning_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fz_tuning_context(cPtr, false);
  }

  public void setStddbg(SWIGTYPE_p_fz_output value) {
    mupdfJNI.fz_context_stddbg_set(swigCPtr, this, SWIGTYPE_p_fz_output.getCPtr(value));
  }

  public SWIGTYPE_p_fz_output getStddbg() {
    long cPtr = mupdfJNI.fz_context_stddbg_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fz_output(cPtr, false);
  }

  public void setFont(SWIGTYPE_p_fz_font_context value) {
    mupdfJNI.fz_context_font_set(swigCPtr, this, SWIGTYPE_p_fz_font_context.getCPtr(value));
  }

  public SWIGTYPE_p_fz_font_context getFont() {
    long cPtr = mupdfJNI.fz_context_font_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fz_font_context(cPtr, false);
  }

  public void setColorspace(SWIGTYPE_p_fz_colorspace_context value) {
    mupdfJNI.fz_context_colorspace_set(swigCPtr, this, SWIGTYPE_p_fz_colorspace_context.getCPtr(value));
  }

  public SWIGTYPE_p_fz_colorspace_context getColorspace() {
    long cPtr = mupdfJNI.fz_context_colorspace_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fz_colorspace_context(cPtr, false);
  }

  public void setStore(SWIGTYPE_p_fz_store value) {
    mupdfJNI.fz_context_store_set(swigCPtr, this, SWIGTYPE_p_fz_store.getCPtr(value));
  }

  public SWIGTYPE_p_fz_store getStore() {
    long cPtr = mupdfJNI.fz_context_store_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fz_store(cPtr, false);
  }

  public void setGlyph_cache(SWIGTYPE_p_fz_glyph_cache value) {
    mupdfJNI.fz_context_glyph_cache_set(swigCPtr, this, SWIGTYPE_p_fz_glyph_cache.getCPtr(value));
  }

  public SWIGTYPE_p_fz_glyph_cache getGlyph_cache() {
    long cPtr = mupdfJNI.fz_context_glyph_cache_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_fz_glyph_cache(cPtr, false);
  }

  public fz_context() {
    this(mupdfJNI.new_fz_context(), true);
  }

}
