/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_colorspace_u_indexed {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_colorspace_u_indexed(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_colorspace_u_indexed obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_colorspace_u_indexed obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_colorspace_u_indexed(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBase(fz_colorspace value) {
    mupdfJNI.fz_colorspace_u_indexed_base_set(swigCPtr, this, fz_colorspace.getCPtr(value), value);
  }

  public fz_colorspace getBase() {
    long cPtr = mupdfJNI.fz_colorspace_u_indexed_base_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace(cPtr, false);
  }

  public void setHigh(int value) {
    mupdfJNI.fz_colorspace_u_indexed_high_set(swigCPtr, this, value);
  }

  public int getHigh() {
    return mupdfJNI.fz_colorspace_u_indexed_high_get(swigCPtr, this);
  }

  public void setLookup(byte[] value) {
    mupdfJNI.fz_colorspace_u_indexed_lookup_set(swigCPtr, this, value);
  }

//  public byte[] getLookup() {
//    long cPtr = mupdfJNI.fz_colorspace_u_indexed_lookup_get(swigCPtr, this);
//    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
//  }

  //public fz_colorspace_u_indexed() {
   // this(mupdfJNI.new_fz_colorspace_u_indexed(), true);
 // }

}
