/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_cookie {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_cookie(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_cookie obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_cookie obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_cookie(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAbort(int value) {
    mupdfJNI.fz_cookie_abort_set(swigCPtr, this, value);
  }

  public int getAbort() {
    return mupdfJNI.fz_cookie_abort_get(swigCPtr, this);
  }

  public void setProgress(int value) {
    mupdfJNI.fz_cookie_progress_set(swigCPtr, this, value);
  }

  public int getProgress() {
    return mupdfJNI.fz_cookie_progress_get(swigCPtr, this);
  }

  public void setProgress_max(int value) {
    mupdfJNI.fz_cookie_progress_max_set(swigCPtr, this, value);
  }

  public int getProgress_max() {
    return mupdfJNI.fz_cookie_progress_max_get(swigCPtr, this);
  }

  public void setErrors(int value) {
    mupdfJNI.fz_cookie_errors_set(swigCPtr, this, value);
  }

  public int getErrors() {
    return mupdfJNI.fz_cookie_errors_get(swigCPtr, this);
  }

  public void setIncomplete(int value) {
    mupdfJNI.fz_cookie_incomplete_set(swigCPtr, this, value);
  }

  public int getIncomplete() {
    return mupdfJNI.fz_cookie_incomplete_get(swigCPtr, this);
  }

  public fz_cookie() {
    this(mupdfJNI.new_fz_cookie(), true);
  }

}
