/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_colorspace_u {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_colorspace_u(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_colorspace_u obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_colorspace_u obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_colorspace_u(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public fz_colorspace_u_indexed getIndexed() {
    long cPtr = mupdfJNI.fz_colorspace_u_indexed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace_u_indexed(cPtr, false);
  }

  public fz_colorspace_u_separation getSeparation() {
    long cPtr = mupdfJNI.fz_colorspace_u_separation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace_u_separation(cPtr, false);
  }

  public fz_colorspace_u() {
    this(mupdfJNI.new_fz_colorspace_u(), true);
  }

}
