/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public final class fz_colorspace_type {
  public final static fz_colorspace_type FZ_COLORSPACE_NONE = new fz_colorspace_type("FZ_COLORSPACE_NONE");
  public final static fz_colorspace_type FZ_COLORSPACE_GRAY = new fz_colorspace_type("FZ_COLORSPACE_GRAY");
  public final static fz_colorspace_type FZ_COLORSPACE_RGB = new fz_colorspace_type("FZ_COLORSPACE_RGB");
  public final static fz_colorspace_type FZ_COLORSPACE_BGR = new fz_colorspace_type("FZ_COLORSPACE_BGR");
  public final static fz_colorspace_type FZ_COLORSPACE_CMYK = new fz_colorspace_type("FZ_COLORSPACE_CMYK");
  public final static fz_colorspace_type FZ_COLORSPACE_LAB = new fz_colorspace_type("FZ_COLORSPACE_LAB");
  public final static fz_colorspace_type FZ_COLORSPACE_INDEXED = new fz_colorspace_type("FZ_COLORSPACE_INDEXED");
  public final static fz_colorspace_type FZ_COLORSPACE_SEPARATION = new fz_colorspace_type("FZ_COLORSPACE_SEPARATION");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static fz_colorspace_type swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + fz_colorspace_type.class + " with value " + swigValue);
  }

  private fz_colorspace_type(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private fz_colorspace_type(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private fz_colorspace_type(String swigName, fz_colorspace_type swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static fz_colorspace_type[] swigValues = { FZ_COLORSPACE_NONE, FZ_COLORSPACE_GRAY, FZ_COLORSPACE_RGB, FZ_COLORSPACE_BGR, FZ_COLORSPACE_CMYK, FZ_COLORSPACE_LAB, FZ_COLORSPACE_INDEXED, FZ_COLORSPACE_SEPARATION };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

