/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_colorspace_u_separation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_colorspace_u_separation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_colorspace_u_separation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_colorspace_u_separation obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_colorspace_u_separation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBase(fz_colorspace value) {
    mupdfJNI.fz_colorspace_u_separation_base_set(swigCPtr, this, fz_colorspace.getCPtr(value), value);
  }

  public fz_colorspace getBase() {
    long cPtr = mupdfJNI.fz_colorspace_u_separation_base_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace(cPtr, false);
  }

  public void setEval(SWIGTYPE_p_f_p_struct_fz_context_p_void_p_q_const__float_int_p_float_int__void value) {
    mupdfJNI.fz_colorspace_u_separation_eval_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_void_p_q_const__float_int_p_float_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_void_p_q_const__float_int_p_float_int__void getEval() {
    long cPtr = mupdfJNI.fz_colorspace_u_separation_eval_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_void_p_q_const__float_int_p_float_int__void(cPtr, false);
  }

  public void setDrop(SWIGTYPE_p_f_p_struct_fz_context_p_void__void value) {
    mupdfJNI.fz_colorspace_u_separation_drop_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_void__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_void__void getDrop() {
    long cPtr = mupdfJNI.fz_colorspace_u_separation_drop_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_void__void(cPtr, false);
  }

  public void setTint(SWIGTYPE_p_void value) {
    mupdfJNI.fz_colorspace_u_separation_tint_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getTint() {
    long cPtr = mupdfJNI.fz_colorspace_u_separation_tint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setColorant(SWIGTYPE_p_p_char value) {
    mupdfJNI.fz_colorspace_u_separation_colorant_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getColorant() {
    long cPtr = mupdfJNI.fz_colorspace_u_separation_colorant_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public fz_colorspace_u_separation() {
    this(mupdfJNI.new_fz_colorspace_u_separation(), true);
  }

}
