/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_color_params {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_color_params(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_color_params obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_color_params obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_color_params(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRi(short value) {
    mupdfJNI.fz_color_params_ri_set(swigCPtr, this, value);
  }

  public short getRi() {
    return mupdfJNI.fz_color_params_ri_get(swigCPtr, this);
  }

  public void setBp(short value) {
    mupdfJNI.fz_color_params_bp_set(swigCPtr, this, value);
  }

  public short getBp() {
    return mupdfJNI.fz_color_params_bp_get(swigCPtr, this);
  }

  public void setOp(short value) {
    mupdfJNI.fz_color_params_op_set(swigCPtr, this, value);
  }

  public short getOp() {
    return mupdfJNI.fz_color_params_op_get(swigCPtr, this);
  }

  public void setOpm(short value) {
    mupdfJNI.fz_color_params_opm_set(swigCPtr, this, value);
  }

  public short getOpm() {
    return mupdfJNI.fz_color_params_opm_get(swigCPtr, this);
  }

  public fz_color_params() {
    this(mupdfJNI.new_fz_color_params(), true);
  }

}
