/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_default_colorspaces {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_default_colorspaces(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_default_colorspaces obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_default_colorspaces obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_default_colorspaces(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRefs(int value) {
    mupdfJNI.fz_default_colorspaces_refs_set(swigCPtr, this, value);
  }

  public int getRefs() {
    return mupdfJNI.fz_default_colorspaces_refs_get(swigCPtr, this);
  }

  public void setGray(fz_colorspace value) {
    mupdfJNI.fz_default_colorspaces_gray_set(swigCPtr, this, fz_colorspace.getCPtr(value), value);
  }

  public fz_colorspace getGray() {
    long cPtr = mupdfJNI.fz_default_colorspaces_gray_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace(cPtr, false);
  }

  public void setRgb(fz_colorspace value) {
    mupdfJNI.fz_default_colorspaces_rgb_set(swigCPtr, this, fz_colorspace.getCPtr(value), value);
  }

  public fz_colorspace getRgb() {
    long cPtr = mupdfJNI.fz_default_colorspaces_rgb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace(cPtr, false);
  }

  public void setCmyk(fz_colorspace value) {
    mupdfJNI.fz_default_colorspaces_cmyk_set(swigCPtr, this, fz_colorspace.getCPtr(value), value);
  }

  public fz_colorspace getCmyk() {
    long cPtr = mupdfJNI.fz_default_colorspaces_cmyk_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace(cPtr, false);
  }

  public void setOi(fz_colorspace value) {
    mupdfJNI.fz_default_colorspaces_oi_set(swigCPtr, this, fz_colorspace.getCPtr(value), value);
  }

  public fz_colorspace getOi() {
    long cPtr = mupdfJNI.fz_default_colorspaces_oi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace(cPtr, false);
  }

  public fz_default_colorspaces() {
    this(mupdfJNI.new_fz_default_colorspaces(), true);
  }

}
