/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_device {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_device(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_device obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_device obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_device(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRefs(int value) {
    mupdfJNI.fz_device_refs_set(swigCPtr, this, value);
  }

  public int getRefs() {
    return mupdfJNI.fz_device_refs_get(swigCPtr, this);
  }

  public void setHints(int value) {
    mupdfJNI.fz_device_hints_set(swigCPtr, this, value);
  }

  public int getHints() {
    return mupdfJNI.fz_device_hints_get(swigCPtr, this);
  }

  public void setFlags(int value) {
    mupdfJNI.fz_device_flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return mupdfJNI.fz_device_flags_get(swigCPtr, this);
  }

  public void setClose_device(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void value) {
    mupdfJNI.fz_device_close_device_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void getClose_device() {
    long cPtr = mupdfJNI.fz_device_close_device_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void(cPtr, false);
  }

  public void setDrop_device(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void value) {
    mupdfJNI.fz_device_drop_device_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void getDrop_device() {
    long cPtr = mupdfJNI.fz_device_drop_device_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void(cPtr, false);
  }

  public void setFill_path(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_int_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void value) {
    mupdfJNI.fz_device_fill_path_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_int_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_int_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void getFill_path() {
    long cPtr = mupdfJNI.fz_device_fill_path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_int_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void(cPtr, false);
  }

  public void setStroke_path(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_p_q_const__fz_stroke_state_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void value) {
    mupdfJNI.fz_device_stroke_path_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_p_q_const__fz_stroke_state_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_p_q_const__fz_stroke_state_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void getStroke_path() {
    long cPtr = mupdfJNI.fz_device_stroke_path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_p_q_const__fz_stroke_state_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void(cPtr, false);
  }

  public void setClip_path(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_int_fz_matrix_fz_rect__void value) {
    mupdfJNI.fz_device_clip_path_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_int_fz_matrix_fz_rect__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_int_fz_matrix_fz_rect__void getClip_path() {
    long cPtr = mupdfJNI.fz_device_clip_path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_int_fz_matrix_fz_rect__void(cPtr, false);
  }

  public void setClip_stroke_path(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_p_q_const__fz_stroke_state_fz_matrix_fz_rect__void value) {
    mupdfJNI.fz_device_clip_stroke_path_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_p_q_const__fz_stroke_state_fz_matrix_fz_rect__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_p_q_const__fz_stroke_state_fz_matrix_fz_rect__void getClip_stroke_path() {
    long cPtr = mupdfJNI.fz_device_clip_stroke_path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_path_p_q_const__fz_stroke_state_fz_matrix_fz_rect__void(cPtr, false);
  }

  public void setFill_text(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void value) {
    mupdfJNI.fz_device_fill_text_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void getFill_text() {
    long cPtr = mupdfJNI.fz_device_fill_text_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void(cPtr, false);
  }

  public void setStroke_text(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_p_q_const__fz_stroke_state_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void value) {
    mupdfJNI.fz_device_stroke_text_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_p_q_const__fz_stroke_state_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_p_q_const__fz_stroke_state_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void getStroke_text() {
    long cPtr = mupdfJNI.fz_device_stroke_text_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_p_q_const__fz_stroke_state_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void(cPtr, false);
  }

  public void setClip_text(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix_fz_rect__void value) {
    mupdfJNI.fz_device_clip_text_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix_fz_rect__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix_fz_rect__void getClip_text() {
    long cPtr = mupdfJNI.fz_device_clip_text_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix_fz_rect__void(cPtr, false);
  }

  public void setClip_stroke_text(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_p_q_const__fz_stroke_state_fz_matrix_fz_rect__void value) {
    mupdfJNI.fz_device_clip_stroke_text_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_p_q_const__fz_stroke_state_fz_matrix_fz_rect__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_p_q_const__fz_stroke_state_fz_matrix_fz_rect__void getClip_stroke_text() {
    long cPtr = mupdfJNI.fz_device_clip_stroke_text_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_p_q_const__fz_stroke_state_fz_matrix_fz_rect__void(cPtr, false);
  }

  public void setIgnore_text(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix__void value) {
    mupdfJNI.fz_device_ignore_text_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix__void getIgnore_text() {
    long cPtr = mupdfJNI.fz_device_ignore_text_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__fz_text_fz_matrix__void(cPtr, false);
  }

  public void setFill_shade(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_shade_fz_matrix_float_fz_color_params__void value) {
    mupdfJNI.fz_device_fill_shade_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_shade_fz_matrix_float_fz_color_params__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_shade_fz_matrix_float_fz_color_params__void getFill_shade() {
    long cPtr = mupdfJNI.fz_device_fill_shade_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_shade_fz_matrix_float_fz_color_params__void(cPtr, false);
  }

  public void setFill_image(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_float_fz_color_params__void value) {
    mupdfJNI.fz_device_fill_image_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_float_fz_color_params__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_float_fz_color_params__void getFill_image() {
    long cPtr = mupdfJNI.fz_device_fill_image_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_float_fz_color_params__void(cPtr, false);
  }

  public void setFill_image_mask(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void value) {
    mupdfJNI.fz_device_fill_image_mask_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void getFill_image_mask() {
    long cPtr = mupdfJNI.fz_device_fill_image_mask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_p_struct_fz_colorspace_p_q_const__float_float_fz_color_params__void(cPtr, false);
  }

  public void setClip_image_mask(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_fz_rect__void value) {
    mupdfJNI.fz_device_clip_image_mask_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_fz_rect__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_fz_rect__void getClip_image_mask() {
    long cPtr = mupdfJNI.fz_device_clip_image_mask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_image_fz_matrix_fz_rect__void(cPtr, false);
  }

  public void setPop_clip(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void value) {
    mupdfJNI.fz_device_pop_clip_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void getPop_clip() {
    long cPtr = mupdfJNI.fz_device_pop_clip_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void(cPtr, false);
  }

  public void setBegin_mask(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_int_p_struct_fz_colorspace_p_q_const__float_fz_color_params__void value) {
    mupdfJNI.fz_device_begin_mask_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_int_p_struct_fz_colorspace_p_q_const__float_fz_color_params__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_int_p_struct_fz_colorspace_p_q_const__float_fz_color_params__void getBegin_mask() {
    long cPtr = mupdfJNI.fz_device_begin_mask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_int_p_struct_fz_colorspace_p_q_const__float_fz_color_params__void(cPtr, false);
  }

  public void setEnd_mask(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_struct_fz_function__void value) {
    mupdfJNI.fz_device_end_mask_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_struct_fz_function__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_struct_fz_function__void getEnd_mask() {
    long cPtr = mupdfJNI.fz_device_end_mask_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_struct_fz_function__void(cPtr, false);
  }

  public void setBegin_group(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_p_struct_fz_colorspace_int_int_int_float__void value) {
    mupdfJNI.fz_device_begin_group_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_p_struct_fz_colorspace_int_int_int_float__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_p_struct_fz_colorspace_int_int_int_float__void getBegin_group() {
    long cPtr = mupdfJNI.fz_device_begin_group_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_p_struct_fz_colorspace_int_int_int_float__void(cPtr, false);
  }

  public void setEnd_group(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void value) {
    mupdfJNI.fz_device_end_group_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void getEnd_group() {
    long cPtr = mupdfJNI.fz_device_end_group_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void(cPtr, false);
  }

  public void setBegin_tile(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_fz_rect_float_float_fz_matrix_int__int value) {
    mupdfJNI.fz_device_begin_tile_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_fz_rect_float_float_fz_matrix_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_fz_rect_float_float_fz_matrix_int__int getBegin_tile() {
    long cPtr = mupdfJNI.fz_device_begin_tile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_fz_rect_fz_rect_float_float_fz_matrix_int__int(cPtr, false);
  }

  public void setEnd_tile(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void value) {
    mupdfJNI.fz_device_end_tile_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void getEnd_tile() {
    long cPtr = mupdfJNI.fz_device_end_tile_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void(cPtr, false);
  }

  public void setRender_flags(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_int_int__void value) {
    mupdfJNI.fz_device_render_flags_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_int_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_int_int__void getRender_flags() {
    long cPtr = mupdfJNI.fz_device_render_flags_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_int_int__void(cPtr, false);
  }

  public void setSet_default_colorspaces(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_default_colorspaces__void value) {
    mupdfJNI.fz_device_set_default_colorspaces_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_default_colorspaces__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_default_colorspaces__void getSet_default_colorspaces() {
    long cPtr = mupdfJNI.fz_device_set_default_colorspaces_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_fz_default_colorspaces__void(cPtr, false);
  }

  public void setBegin_layer(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__char__void value) {
    mupdfJNI.fz_device_begin_layer_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__char__void getBegin_layer() {
    long cPtr = mupdfJNI.fz_device_begin_layer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_p_q_const__char__void(cPtr, false);
  }

  public void setEnd_layer(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void value) {
    mupdfJNI.fz_device_end_layer_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void getEnd_layer() {
    long cPtr = mupdfJNI.fz_device_end_layer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void(cPtr, false);
  }

  public void setBegin_structure(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_enum_fz_structure_p_q_const__char_int__void value) {
    mupdfJNI.fz_device_begin_structure_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_enum_fz_structure_p_q_const__char_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_enum_fz_structure_p_q_const__char_int__void getBegin_structure() {
    long cPtr = mupdfJNI.fz_device_begin_structure_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_enum_fz_structure_p_q_const__char_int__void(cPtr, false);
  }

  public void setEnd_structure(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void value) {
    mupdfJNI.fz_device_end_structure_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void getEnd_structure() {
    long cPtr = mupdfJNI.fz_device_end_structure_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void(cPtr, false);
  }

  public void setBegin_metatext(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_enum_fz_metatext_p_q_const__char__void value) {
    mupdfJNI.fz_device_begin_metatext_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_enum_fz_metatext_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_enum_fz_metatext_p_q_const__char__void getBegin_metatext() {
    long cPtr = mupdfJNI.fz_device_begin_metatext_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device_enum_fz_metatext_p_q_const__char__void(cPtr, false);
  }

  public void setEnd_metatext(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void value) {
    mupdfJNI.fz_device_end_metatext_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void getEnd_metatext() {
    long cPtr = mupdfJNI.fz_device_end_metatext_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_device__void(cPtr, false);
  }

  public void setD1_rect(fz_rect value) {
    mupdfJNI.fz_device_d1_rect_set(swigCPtr, this, fz_rect.getCPtr(value), value);
  }

  public fz_rect getD1_rect() {
    long cPtr = mupdfJNI.fz_device_d1_rect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_rect(cPtr, false);
  }

  public void setContainer_len(int value) {
    mupdfJNI.fz_device_container_len_set(swigCPtr, this, value);
  }

  public int getContainer_len() {
    return mupdfJNI.fz_device_container_len_get(swigCPtr, this);
  }

  public void setContainer_cap(int value) {
    mupdfJNI.fz_device_container_cap_set(swigCPtr, this, value);
  }

  public int getContainer_cap() {
    return mupdfJNI.fz_device_container_cap_get(swigCPtr, this);
  }

  public void setContainer(fz_device_container_stack value) {
    mupdfJNI.fz_device_container_set(swigCPtr, this, fz_device_container_stack.getCPtr(value), value);
  }

  public fz_device_container_stack getContainer() {
    long cPtr = mupdfJNI.fz_device_container_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_device_container_stack(cPtr, false);
  }

  public fz_device() {
    this(mupdfJNI.new_fz_device(), true);
  }

}
