/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_document_handler {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_document_handler(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_document_handler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_document_handler obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_document_handler(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRecognize(SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_q_const__char__int value) {
    mupdfJNI.fz_document_handler_recognize_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_q_const__char__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_q_const__char__int getRecognize() {
    long cPtr = mupdfJNI.fz_document_handler_recognize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_q_const__char__int(cPtr, false);
  }

  public void setOpen(SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_struct_fz_stream_p_struct_fz_stream_p_fz_archive_p_void__p_fz_document value) {
    mupdfJNI.fz_document_handler_open_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_struct_fz_stream_p_struct_fz_stream_p_fz_archive_p_void__p_fz_document.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_struct_fz_stream_p_struct_fz_stream_p_fz_archive_p_void__p_fz_document getOpen() {
    long cPtr = mupdfJNI.fz_document_handler_open_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_struct_fz_stream_p_struct_fz_stream_p_fz_archive_p_void__p_fz_document(cPtr, false);
  }

  public void setExtensions(SWIGTYPE_p_p_char value) {
    mupdfJNI.fz_document_handler_extensions_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getExtensions() {
    long cPtr = mupdfJNI.fz_document_handler_extensions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setMimetypes(SWIGTYPE_p_p_char value) {
    mupdfJNI.fz_document_handler_mimetypes_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getMimetypes() {
    long cPtr = mupdfJNI.fz_document_handler_mimetypes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setRecognize_content(SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_struct_fz_stream_p_fz_archive_p_p_void_p_p_f_p_struct_fz_context_p_void__void__int value) {
    mupdfJNI.fz_document_handler_recognize_content_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_struct_fz_stream_p_fz_archive_p_p_void_p_p_f_p_struct_fz_context_p_void__void__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_struct_fz_stream_p_fz_archive_p_p_void_p_p_f_p_struct_fz_context_p_void__void__int getRecognize_content() {
    long cPtr = mupdfJNI.fz_document_handler_recognize_content_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler_p_struct_fz_stream_p_fz_archive_p_p_void_p_p_f_p_struct_fz_context_p_void__void__int(cPtr, false);
  }

  public void setWants_dir(int value) {
    mupdfJNI.fz_document_handler_wants_dir_set(swigCPtr, this, value);
  }

  public int getWants_dir() {
    return mupdfJNI.fz_document_handler_wants_dir_get(swigCPtr, this);
  }

  public void setWants_file(int value) {
    mupdfJNI.fz_document_handler_wants_file_set(swigCPtr, this, value);
  }

  public int getWants_file() {
    return mupdfJNI.fz_document_handler_wants_file_get(swigCPtr, this);
  }

  public void setFin(SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler__void value) {
    mupdfJNI.fz_document_handler_fin_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler__void getFin() {
    long cPtr = mupdfJNI.fz_document_handler_fin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_q_const__struct_fz_document_handler__void(cPtr, false);
  }

  public fz_document_handler() {
    this(mupdfJNI.new_fz_document_handler(), true);
  }

}
