/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_draw_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_draw_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_draw_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_draw_options obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_draw_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRotate(int value) {
    mupdfJNI.fz_draw_options_rotate_set(swigCPtr, this, value);
  }

  public int getRotate() {
    return mupdfJNI.fz_draw_options_rotate_get(swigCPtr, this);
  }

  public void setX_resolution(int value) {
    mupdfJNI.fz_draw_options_x_resolution_set(swigCPtr, this, value);
  }

  public int getX_resolution() {
    return mupdfJNI.fz_draw_options_x_resolution_get(swigCPtr, this);
  }

  public void setY_resolution(int value) {
    mupdfJNI.fz_draw_options_y_resolution_set(swigCPtr, this, value);
  }

  public int getY_resolution() {
    return mupdfJNI.fz_draw_options_y_resolution_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    mupdfJNI.fz_draw_options_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return mupdfJNI.fz_draw_options_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    mupdfJNI.fz_draw_options_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return mupdfJNI.fz_draw_options_height_get(swigCPtr, this);
  }

  public void setColorspace(fz_colorspace value) {
    mupdfJNI.fz_draw_options_colorspace_set(swigCPtr, this, fz_colorspace.getCPtr(value), value);
  }

  public fz_colorspace getColorspace() {
    long cPtr = mupdfJNI.fz_draw_options_colorspace_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_colorspace(cPtr, false);
  }

  public void setAlpha(int value) {
    mupdfJNI.fz_draw_options_alpha_set(swigCPtr, this, value);
  }

  public int getAlpha() {
    return mupdfJNI.fz_draw_options_alpha_get(swigCPtr, this);
  }

  public void setGraphics(int value) {
    mupdfJNI.fz_draw_options_graphics_set(swigCPtr, this, value);
  }

  public int getGraphics() {
    return mupdfJNI.fz_draw_options_graphics_get(swigCPtr, this);
  }

  public void setText(int value) {
    mupdfJNI.fz_draw_options_text_set(swigCPtr, this, value);
  }

  public int getText() {
    return mupdfJNI.fz_draw_options_text_get(swigCPtr, this);
  }

  public fz_draw_options() {
    this(mupdfJNI.new_fz_draw_options(), true);
  }

}
