/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_device_container_stack {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_device_container_stack(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_device_container_stack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_device_container_stack obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_device_container_stack(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setScissor(fz_rect value) {
    mupdfJNI.fz_device_container_stack_scissor_set(swigCPtr, this, fz_rect.getCPtr(value), value);
  }

  public fz_rect getScissor() {
    long cPtr = mupdfJNI.fz_device_container_stack_scissor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_rect(cPtr, false);
  }

  public void setType(int value) {
    mupdfJNI.fz_device_container_stack_type_set(swigCPtr, this, value);
  }

  public int getType() {
    return mupdfJNI.fz_device_container_stack_type_get(swigCPtr, this);
  }

  public void setUser(int value) {
    mupdfJNI.fz_device_container_stack_user_set(swigCPtr, this, value);
  }

  public int getUser() {
    return mupdfJNI.fz_device_container_stack_user_get(swigCPtr, this);
  }

  public fz_device_container_stack() {
    this(mupdfJNI.new_fz_device_container_stack(), true);
  }

}
