/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_document {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_document(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_document obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_document obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_document(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRefs(int value) {
    mupdfJNI.fz_document_refs_set(swigCPtr, this, value);
  }

  public int getRefs() {
    return mupdfJNI.fz_document_refs_get(swigCPtr, this);
  }

  public void setDrop_document(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__void value) {
    mupdfJNI.fz_document_drop_document_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__void getDrop_document() {
    long cPtr = mupdfJNI.fz_document_drop_document_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__void(cPtr, false);
  }

  public void setNeeds_password(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__int value) {
    mupdfJNI.fz_document_needs_password_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__int getNeeds_password() {
    long cPtr = mupdfJNI.fz_document_needs_password_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__int(cPtr, false);
  }

  public void setAuthenticate_password(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char__int value) {
    mupdfJNI.fz_document_authenticate_password_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char__int getAuthenticate_password() {
    long cPtr = mupdfJNI.fz_document_authenticate_password_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char__int(cPtr, false);
  }

  public void setHas_permission(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_enum_fz_permission__int value) {
    mupdfJNI.fz_document_has_permission_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_enum_fz_permission__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_enum_fz_permission__int getHas_permission() {
    long cPtr = mupdfJNI.fz_document_has_permission_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_enum_fz_permission__int(cPtr, false);
  }

  public void setLoad_outline(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_outline value) {
    mupdfJNI.fz_document_load_outline_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_outline.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_outline getLoad_outline() {
    long cPtr = mupdfJNI.fz_document_load_outline_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_outline(cPtr, false);
  }

  public void setOutline_iterator(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_outline_iterator value) {
    mupdfJNI.fz_document_outline_iterator_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_outline_iterator.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_outline_iterator getOutline_iterator() {
    long cPtr = mupdfJNI.fz_document_outline_iterator_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_outline_iterator(cPtr, false);
  }

  public void setLayout(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_float_float_float__void value) {
    mupdfJNI.fz_document_layout_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_float_float_float__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_float_float_float__void getLayout() {
    long cPtr = mupdfJNI.fz_document_layout_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_float_float_float__void(cPtr, false);
  }

  public void setMake_bookmark(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_fz_location__int value) {
    mupdfJNI.fz_document_make_bookmark_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_fz_location__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_fz_location__int getMake_bookmark() {
    long cPtr = mupdfJNI.fz_document_make_bookmark_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_fz_location__int(cPtr, false);
  }

  public void setLookup_bookmark(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int__fz_location value) {
    mupdfJNI.fz_document_lookup_bookmark_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int__fz_location.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int__fz_location getLookup_bookmark() {
    long cPtr = mupdfJNI.fz_document_lookup_bookmark_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int__fz_location(cPtr, false);
  }

  public void setResolve_link_dest(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char__fz_link_dest value) {
    mupdfJNI.fz_document_resolve_link_dest_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char__fz_link_dest.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char__fz_link_dest getResolve_link_dest() {
    long cPtr = mupdfJNI.fz_document_resolve_link_dest_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char__fz_link_dest(cPtr, false);
  }

  public void setFormat_link_uri(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_fz_link_dest__p_char value) {
    mupdfJNI.fz_document_format_link_uri_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_fz_link_dest__p_char.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_fz_link_dest__p_char getFormat_link_uri() {
    long cPtr = mupdfJNI.fz_document_format_link_uri_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_fz_link_dest__p_char(cPtr, false);
  }

  public void setCount_chapters(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__int value) {
    mupdfJNI.fz_document_count_chapters_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__int getCount_chapters() {
    long cPtr = mupdfJNI.fz_document_count_chapters_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__int(cPtr, false);
  }

  public void setCount_pages(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int__int value) {
    mupdfJNI.fz_document_count_pages_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int__int getCount_pages() {
    long cPtr = mupdfJNI.fz_document_count_pages_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int__int(cPtr, false);
  }

  public void setLoad_page(SWIGTYPE_p_f_p_fz_context_p_fz_document_int_int__p_fz_page value) {
    mupdfJNI.fz_document_load_page_set(swigCPtr, this, SWIGTYPE_p_f_p_fz_context_p_fz_document_int_int__p_fz_page.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_fz_context_p_fz_document_int_int__p_fz_page getLoad_page() {
    long cPtr = mupdfJNI.fz_document_load_page_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_fz_context_p_fz_document_int_int__p_fz_page(cPtr, false);
  }

  public void setPage_label(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int_int_p_char_size_t__void value) {
    mupdfJNI.fz_document_page_label_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int_int_p_char_size_t__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int_int_p_char_size_t__void getPage_label() {
    long cPtr = mupdfJNI.fz_document_page_label_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_int_int_p_char_size_t__void(cPtr, false);
  }

  public void setLookup_metadata(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char_p_char_size_t__int value) {
    mupdfJNI.fz_document_lookup_metadata_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char_p_char_size_t__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char_p_char_size_t__int getLookup_metadata() {
    long cPtr = mupdfJNI.fz_document_lookup_metadata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char_p_char_size_t__int(cPtr, false);
  }

  public void setSet_metadata(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char_p_q_const__char__void value) {
    mupdfJNI.fz_document_set_metadata_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char_p_q_const__char__void getSet_metadata() {
    long cPtr = mupdfJNI.fz_document_set_metadata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_q_const__char_p_q_const__char__void(cPtr, false);
  }

  public void setGet_output_intent(SWIGTYPE_p_f_p_fz_context_p_fz_document__p_fz_colorspace value) {
    mupdfJNI.fz_document_get_output_intent_set(swigCPtr, this, SWIGTYPE_p_f_p_fz_context_p_fz_document__p_fz_colorspace.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_fz_context_p_fz_document__p_fz_colorspace getGet_output_intent() {
    long cPtr = mupdfJNI.fz_document_get_output_intent_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_fz_context_p_fz_document__p_fz_colorspace(cPtr, false);
  }

  public void setOutput_accelerator(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_struct_fz_output__void value) {
    mupdfJNI.fz_document_output_accelerator_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_struct_fz_output__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_struct_fz_output__void getOutput_accelerator() {
    long cPtr = mupdfJNI.fz_document_output_accelerator_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_struct_fz_output__void(cPtr, false);
  }

  public void setRun_structure(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_struct_fz_device_p_fz_cookie__void value) {
    mupdfJNI.fz_document_run_structure_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_struct_fz_device_p_fz_cookie__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_struct_fz_device_p_fz_cookie__void getRun_structure() {
    long cPtr = mupdfJNI.fz_document_run_structure_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document_p_struct_fz_device_p_fz_cookie__void(cPtr, false);
  }

  public void setAs_pdf(SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_document value) {
    mupdfJNI.fz_document_as_pdf_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_document.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_document getAs_pdf() {
    long cPtr = mupdfJNI.fz_document_as_pdf_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_fz_document__p_fz_document(cPtr, false);
  }

  public void setDid_layout(int value) {
    mupdfJNI.fz_document_did_layout_set(swigCPtr, this, value);
  }

  public int getDid_layout() {
    return mupdfJNI.fz_document_did_layout_get(swigCPtr, this);
  }

  public void setIs_reflowable(int value) {
    mupdfJNI.fz_document_is_reflowable_set(swigCPtr, this, value);
  }

  public int getIs_reflowable() {
    return mupdfJNI.fz_document_is_reflowable_get(swigCPtr, this);
  }

  public void setOpen(fz_page value) {
    mupdfJNI.fz_document_open_set(swigCPtr, this, fz_page.getCPtr(value), value);
  }

  public fz_page getOpen() {
    long cPtr = mupdfJNI.fz_document_open_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_page(cPtr, false);
  }

  public fz_document() {
    this(mupdfJNI.new_fz_document(), true);
  }

}
