/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_error_stack_slot {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_error_stack_slot(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_error_stack_slot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_error_stack_slot obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_error_stack_slot(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBuffer(SWIGTYPE_p_jmp_buf value) {
    mupdfJNI.fz_error_stack_slot_buffer_set(swigCPtr, this, SWIGTYPE_p_jmp_buf.getCPtr(value));
  }

  public SWIGTYPE_p_jmp_buf getBuffer() {
    return new SWIGTYPE_p_jmp_buf(mupdfJNI.fz_error_stack_slot_buffer_get(swigCPtr, this), true);
  }

  public void setState(int value) {
    mupdfJNI.fz_error_stack_slot_state_set(swigCPtr, this, value);
  }

  public int getState() {
    return mupdfJNI.fz_error_stack_slot_state_get(swigCPtr, this);
  }

  public void setCode(int value) {
    mupdfJNI.fz_error_stack_slot_code_set(swigCPtr, this, value);
  }

  public int getCode() {
    return mupdfJNI.fz_error_stack_slot_code_get(swigCPtr, this);
  }

  public void setPadding(byte[] value) {
    mupdfJNI.fz_error_stack_slot_padding_set(swigCPtr, this, value);
  }

  public byte[] getPadding() {
    return mupdfJNI.fz_error_stack_slot_padding_get(swigCPtr, this);
  }

  public fz_error_stack_slot() {
    this(mupdfJNI.new_fz_error_stack_slot(), true);
  }

}
