/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_error_context {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_error_context(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_error_context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_error_context obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_error_context(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTop(fz_error_stack_slot value) {
    mupdfJNI.fz_error_context_top_set(swigCPtr, this, fz_error_stack_slot.getCPtr(value), value);
  }

  public fz_error_stack_slot getTop() {
    long cPtr = mupdfJNI.fz_error_context_top_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_error_stack_slot(cPtr, false);
  }

  public void setStack(fz_error_stack_slot value) {
    mupdfJNI.fz_error_context_stack_set(swigCPtr, this, fz_error_stack_slot.getCPtr(value), value);
  }

  public fz_error_stack_slot getStack() {
    long cPtr = mupdfJNI.fz_error_context_stack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_error_stack_slot(cPtr, false);
  }

  public void setPadding(fz_error_stack_slot value) {
    mupdfJNI.fz_error_context_padding_set(swigCPtr, this, fz_error_stack_slot.getCPtr(value), value);
  }

  public fz_error_stack_slot getPadding() {
    long cPtr = mupdfJNI.fz_error_context_padding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_error_stack_slot(cPtr, false);
  }

  public void setStack_base(fz_error_stack_slot value) {
    mupdfJNI.fz_error_context_stack_base_set(swigCPtr, this, fz_error_stack_slot.getCPtr(value), value);
  }

  public fz_error_stack_slot getStack_base() {
    long cPtr = mupdfJNI.fz_error_context_stack_base_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_error_stack_slot(cPtr, false);
  }

  public void setErrcode(int value) {
    mupdfJNI.fz_error_context_errcode_set(swigCPtr, this, value);
  }

  public int getErrcode() {
    return mupdfJNI.fz_error_context_errcode_get(swigCPtr, this);
  }

  public void setErrnum(int value) {
    mupdfJNI.fz_error_context_errnum_set(swigCPtr, this, value);
  }

  public int getErrnum() {
    return mupdfJNI.fz_error_context_errnum_get(swigCPtr, this);
  }

  public void setPrint_user(SWIGTYPE_p_void value) {
    mupdfJNI.fz_error_context_print_user_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getPrint_user() {
    long cPtr = mupdfJNI.fz_error_context_print_user_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setPrint(SWIGTYPE_p_f_p_void_p_q_const__char__void value) {
    mupdfJNI.fz_error_context_print_set(swigCPtr, this, SWIGTYPE_p_f_p_void_p_q_const__char__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_p_q_const__char__void getPrint() {
    long cPtr = mupdfJNI.fz_error_context_print_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_p_q_const__char__void(cPtr, false);
  }

  public void setMessage(byte[] value) {
    mupdfJNI.fz_error_context_message_set(swigCPtr, this, value);
  }

  public byte[] getMessage() {
    return mupdfJNI.fz_error_context_message_get(swigCPtr, this);
  }

  public fz_error_context() {
    this(mupdfJNI.new_fz_error_context(), true);
  }

}
