/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_function {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_function(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_function obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_function obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_function(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStorable(SWIGTYPE_p_fz_storable value) {
    mupdfJNI.fz_function_storable_set(swigCPtr, this, SWIGTYPE_p_fz_storable.getCPtr(value));
  }

  public SWIGTYPE_p_fz_storable getStorable() {
    return new SWIGTYPE_p_fz_storable(mupdfJNI.fz_function_storable_get(swigCPtr, this), true);
  }

  public void setSize(int value) {
    mupdfJNI.fz_function_size_set(swigCPtr, this, value);
  }

  public int getSize() {
    return mupdfJNI.fz_function_size_get(swigCPtr, this);
  }

  public void setM(int value) {
    mupdfJNI.fz_function_m_set(swigCPtr, this, value);
  }

  public int getM() {
    return mupdfJNI.fz_function_m_get(swigCPtr, this);
  }

  public void setN(int value) {
    mupdfJNI.fz_function_n_set(swigCPtr, this, value);
  }

  public int getN() {
    return mupdfJNI.fz_function_n_get(swigCPtr, this);
  }

  public void setEval(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_function_p_q_const__float_p_float__void value) {
    mupdfJNI.fz_function_eval_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_function_p_q_const__float_p_float__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_function_p_q_const__float_p_float__void getEval() {
    long cPtr = mupdfJNI.fz_function_eval_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_function_p_q_const__float_p_float__void(cPtr, false);
  }

  public fz_function() {
    this(mupdfJNI.new_fz_function(), true);
  }

}
