/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_irect {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_irect(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_irect obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_irect obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_irect(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX0(int value) {
    mupdfJNI.fz_irect_x0_set(swigCPtr, this, value);
  }

  public int getX0() {
    return mupdfJNI.fz_irect_x0_get(swigCPtr, this);
  }

  public void setY0(int value) {
    mupdfJNI.fz_irect_y0_set(swigCPtr, this, value);
  }

  public int getY0() {
    return mupdfJNI.fz_irect_y0_get(swigCPtr, this);
  }

  public void setX1(int value) {
    mupdfJNI.fz_irect_x1_set(swigCPtr, this, value);
  }

  public int getX1() {
    return mupdfJNI.fz_irect_x1_get(swigCPtr, this);
  }

  public void setY1(int value) {
    mupdfJNI.fz_irect_y1_set(swigCPtr, this, value);
  }

  public int getY1() {
    return mupdfJNI.fz_irect_y1_get(swigCPtr, this);
  }

  public fz_irect() {
    this(mupdfJNI.new_fz_irect(), true);
  }

}
