/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_locks_context {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_locks_context(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_locks_context obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_locks_context obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_locks_context(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUser(SWIGTYPE_p_void value) {
    mupdfJNI.fz_locks_context_user_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUser() {
    long cPtr = mupdfJNI.fz_locks_context_user_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setLock(SWIGTYPE_p_f_p_void_int__void value) {
    mupdfJNI.fz_locks_context_lock_set(swigCPtr, this, SWIGTYPE_p_f_p_void_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_int__void getLock() {
    long cPtr = mupdfJNI.fz_locks_context_lock_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_int__void(cPtr, false);
  }

  public void setUnlock(SWIGTYPE_p_f_p_void_int__void value) {
    mupdfJNI.fz_locks_context_unlock_set(swigCPtr, this, SWIGTYPE_p_f_p_void_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_void_int__void getUnlock() {
    long cPtr = mupdfJNI.fz_locks_context_unlock_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_void_int__void(cPtr, false);
  }

  public fz_locks_context() {
    this(mupdfJNI.new_fz_locks_context(), true);
  }

}
