/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_matrix {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_matrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_matrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_matrix obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_matrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setA(float value) {
    mupdfJNI.fz_matrix_a_set(swigCPtr, this, value);
  }

  public float getA() {
    return mupdfJNI.fz_matrix_a_get(swigCPtr, this);
  }

  public void setB(float value) {
    mupdfJNI.fz_matrix_b_set(swigCPtr, this, value);
  }

  public float getB() {
    return mupdfJNI.fz_matrix_b_get(swigCPtr, this);
  }

  public void setC(float value) {
    mupdfJNI.fz_matrix_c_set(swigCPtr, this, value);
  }

  public float getC() {
    return mupdfJNI.fz_matrix_c_get(swigCPtr, this);
  }

  public void setD(float value) {
    mupdfJNI.fz_matrix_d_set(swigCPtr, this, value);
  }

  public float getD() {
    return mupdfJNI.fz_matrix_d_get(swigCPtr, this);
  }

  public void setE(float value) {
    mupdfJNI.fz_matrix_e_set(swigCPtr, this, value);
  }

  public float getE() {
    return mupdfJNI.fz_matrix_e_get(swigCPtr, this);
  }

  public void setF(float value) {
    mupdfJNI.fz_matrix_f_set(swigCPtr, this, value);
  }

  public float getF() {
    return mupdfJNI.fz_matrix_f_get(swigCPtr, this);
  }

  public fz_matrix() {
    this(mupdfJNI.new_fz_matrix(), true);
  }

}
