/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public final class fz_metatext {
  public final static fz_metatext FZ_METATEXT_ACTUALTEXT = new fz_metatext("FZ_METATEXT_ACTUALTEXT");
  public final static fz_metatext FZ_METATEXT_ALT = new fz_metatext("FZ_METATEXT_ALT");
  public final static fz_metatext FZ_METATEXT_ABBREVIATION = new fz_metatext("FZ_METATEXT_ABBREVIATION");
  public final static fz_metatext FZ_METATEXT_TITLE = new fz_metatext("FZ_METATEXT_TITLE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static fz_metatext swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + fz_metatext.class + " with value " + swigValue);
  }

  private fz_metatext(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private fz_metatext(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private fz_metatext(String swigName, fz_metatext swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static fz_metatext[] swigValues = { FZ_METATEXT_ACTUALTEXT, FZ_METATEXT_ALT, FZ_METATEXT_ABBREVIATION, FZ_METATEXT_TITLE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

