/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_point {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_point(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_point obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_point obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_point(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    mupdfJNI.fz_point_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return mupdfJNI.fz_point_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    mupdfJNI.fz_point_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return mupdfJNI.fz_point_y_get(swigCPtr, this);
  }

  public fz_point() {
    this(mupdfJNI.new_fz_point(), true);
  }

}
