/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public final class fz_permission {
  public final static fz_permission FZ_PERMISSION_PRINT = new fz_permission("FZ_PERMISSION_PRINT", mupdfJNI.FZ_PERMISSION_PRINT_get());
  public final static fz_permission FZ_PERMISSION_COPY = new fz_permission("FZ_PERMISSION_COPY", mupdfJNI.FZ_PERMISSION_COPY_get());
  public final static fz_permission FZ_PERMISSION_EDIT = new fz_permission("FZ_PERMISSION_EDIT", mupdfJNI.FZ_PERMISSION_EDIT_get());
  public final static fz_permission FZ_PERMISSION_ANNOTATE = new fz_permission("FZ_PERMISSION_ANNOTATE", mupdfJNI.FZ_PERMISSION_ANNOTATE_get());
  public final static fz_permission FZ_PERMISSION_FORM = new fz_permission("FZ_PERMISSION_FORM", mupdfJNI.FZ_PERMISSION_FORM_get());
  public final static fz_permission FZ_PERMISSION_ACCESSIBILITY = new fz_permission("FZ_PERMISSION_ACCESSIBILITY", mupdfJNI.FZ_PERMISSION_ACCESSIBILITY_get());
  public final static fz_permission FZ_PERMISSION_ASSEMBLE = new fz_permission("FZ_PERMISSION_ASSEMBLE", mupdfJNI.FZ_PERMISSION_ASSEMBLE_get());
  public final static fz_permission FZ_PERMISSION_PRINT_HQ = new fz_permission("FZ_PERMISSION_PRINT_HQ", mupdfJNI.FZ_PERMISSION_PRINT_HQ_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static fz_permission swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + fz_permission.class + " with value " + swigValue);
  }

  private fz_permission(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private fz_permission(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private fz_permission(String swigName, fz_permission swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static fz_permission[] swigValues = { FZ_PERMISSION_PRINT, FZ_PERMISSION_COPY, FZ_PERMISSION_EDIT, FZ_PERMISSION_ANNOTATE, FZ_PERMISSION_FORM, FZ_PERMISSION_ACCESSIBILITY, FZ_PERMISSION_ASSEMBLE, FZ_PERMISSION_PRINT_HQ };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

