/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_page {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_page(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_page obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_page obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_page(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRefs(int value) {
    mupdfJNI.fz_page_refs_set(swigCPtr, this, value);
  }

  public int getRefs() {
    return mupdfJNI.fz_page_refs_get(swigCPtr, this);
  }

  public void setDoc(fz_document value) {
    mupdfJNI.fz_page_doc_set(swigCPtr, this, fz_document.getCPtr(value), value);
  }

  public fz_document getDoc() {
    long cPtr = mupdfJNI.fz_page_doc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_document(cPtr, false);
  }

  public void setChapter(int value) {
    mupdfJNI.fz_page_chapter_set(swigCPtr, this, value);
  }

  public int getChapter() {
    return mupdfJNI.fz_page_chapter_get(swigCPtr, this);
  }

  public void setNumber(int value) {
    mupdfJNI.fz_page_number_set(swigCPtr, this, value);
  }

  public int getNumber() {
    return mupdfJNI.fz_page_number_get(swigCPtr, this);
  }

  public void setIncomplete(int value) {
    mupdfJNI.fz_page_incomplete_set(swigCPtr, this, value);
  }

  public int getIncomplete() {
    return mupdfJNI.fz_page_incomplete_get(swigCPtr, this);
  }

  public void setDrop_page(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__void value) {
    mupdfJNI.fz_page_drop_page_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__void getDrop_page() {
    long cPtr = mupdfJNI.fz_page_drop_page_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__void(cPtr, false);
  }

  public void setBound_page(SWIGTYPE_p_f_p_fz_context_p_fz_page_fz_box_type__fz_rect value) {
    mupdfJNI.fz_page_bound_page_set(swigCPtr, this, SWIGTYPE_p_f_p_fz_context_p_fz_page_fz_box_type__fz_rect.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_fz_context_p_fz_page_fz_box_type__fz_rect getBound_page() {
    long cPtr = mupdfJNI.fz_page_bound_page_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_fz_context_p_fz_page_fz_box_type__fz_rect(cPtr, false);
  }

  public void setRun_page_contents(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void value) {
    mupdfJNI.fz_page_run_page_contents_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void getRun_page_contents() {
    long cPtr = mupdfJNI.fz_page_run_page_contents_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void(cPtr, false);
  }

  public void setRun_page_annots(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void value) {
    mupdfJNI.fz_page_run_page_annots_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void getRun_page_annots() {
    long cPtr = mupdfJNI.fz_page_run_page_annots_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void(cPtr, false);
  }

  public void setRun_page_widgets(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void value) {
    mupdfJNI.fz_page_run_page_widgets_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void getRun_page_widgets() {
    long cPtr = mupdfJNI.fz_page_run_page_widgets_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_struct_fz_device_fz_matrix_p_fz_cookie__void(cPtr, false);
  }

  public void setLoad_links(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__p_fz_link value) {
    mupdfJNI.fz_page_load_links_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__p_fz_link.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__p_fz_link getLoad_links() {
    long cPtr = mupdfJNI.fz_page_load_links_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__p_fz_link(cPtr, false);
  }

  public void setPage_presentation(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_transition_p_float__p_fz_transition value) {
    mupdfJNI.fz_page_page_presentation_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_transition_p_float__p_fz_transition.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_transition_p_float__p_fz_transition getPage_presentation() {
    long cPtr = mupdfJNI.fz_page_page_presentation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_transition_p_float__p_fz_transition(cPtr, false);
  }

  public void setControl_separation(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_int_int__void value) {
    mupdfJNI.fz_page_control_separation_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_int_int__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_int_int__void getControl_separation() {
    long cPtr = mupdfJNI.fz_page_control_separation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_int_int__void(cPtr, false);
  }

  public void setSeparation_disabled(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_int__int value) {
    mupdfJNI.fz_page_separation_disabled_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_int__int getSeparation_disabled() {
    long cPtr = mupdfJNI.fz_page_separation_disabled_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_int__int(cPtr, false);
  }

  public void setSeparations(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__p_fz_separations value) {
    mupdfJNI.fz_page_separations_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__p_fz_separations.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__p_fz_separations getSeparations() {
    long cPtr = mupdfJNI.fz_page_separations_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__p_fz_separations(cPtr, false);
  }

  public void setOverprint(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__int value) {
    mupdfJNI.fz_page_overprint_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__int getOverprint() {
    long cPtr = mupdfJNI.fz_page_overprint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page__int(cPtr, false);
  }

  public void setCreate_link(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_fz_rect_p_q_const__char__p_fz_link value) {
    mupdfJNI.fz_page_create_link_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_fz_rect_p_q_const__char__p_fz_link.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_fz_rect_p_q_const__char__p_fz_link getCreate_link() {
    long cPtr = mupdfJNI.fz_page_create_link_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_fz_rect_p_q_const__char__p_fz_link(cPtr, false);
  }

  public void setDelete_link(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_link__void value) {
    mupdfJNI.fz_page_delete_link_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_link__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_link__void getDelete_link() {
    long cPtr = mupdfJNI.fz_page_delete_link_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_link__void(cPtr, false);
  }

  public void setPrev(SWIGTYPE_p_p_fz_page value) {
    mupdfJNI.fz_page_prev_set(swigCPtr, this, SWIGTYPE_p_p_fz_page.getCPtr(value));
  }

  public SWIGTYPE_p_p_fz_page getPrev() {
    long cPtr = mupdfJNI.fz_page_prev_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_fz_page(cPtr, false);
  }

  public void setNext(fz_page value) {
    mupdfJNI.fz_page_next_set(swigCPtr, this, fz_page.getCPtr(value), value);
  }

  public fz_page getNext() {
    long cPtr = mupdfJNI.fz_page_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_page(cPtr, false);
  }

  public fz_page() {
    this(mupdfJNI.new_fz_page(), true);
  }

}
