/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_quad {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_quad(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_quad obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_quad obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_quad(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUl(fz_point value) {
    mupdfJNI.fz_quad_ul_set(swigCPtr, this, fz_point.getCPtr(value), value);
  }

  public fz_point getUl() {
    long cPtr = mupdfJNI.fz_quad_ul_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_point(cPtr, false);
  }

  public void setUr(fz_point value) {
    mupdfJNI.fz_quad_ur_set(swigCPtr, this, fz_point.getCPtr(value), value);
  }

  public fz_point getUr() {
    long cPtr = mupdfJNI.fz_quad_ur_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_point(cPtr, false);
  }

  public void setLl(fz_point value) {
    mupdfJNI.fz_quad_ll_set(swigCPtr, this, fz_point.getCPtr(value), value);
  }

  public fz_point getLl() {
    long cPtr = mupdfJNI.fz_quad_ll_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_point(cPtr, false);
  }

  public void setLr(fz_point value) {
    mupdfJNI.fz_quad_lr_set(swigCPtr, this, fz_point.getCPtr(value), value);
  }

  public fz_point getLr() {
    long cPtr = mupdfJNI.fz_quad_lr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new fz_point(cPtr, false);
  }

  public fz_quad() {
    this(mupdfJNI.new_fz_quad(), true);
  }

}
