/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public final class fz_structure {
  public final static fz_structure FZ_STRUCTURE_INVALID = new fz_structure("FZ_STRUCTURE_INVALID", mupdfJNI.FZ_STRUCTURE_INVALID_get());
  public final static fz_structure FZ_STRUCTURE_DOCUMENT = new fz_structure("FZ_STRUCTURE_DOCUMENT");
  public final static fz_structure FZ_STRUCTURE_PART = new fz_structure("FZ_STRUCTURE_PART");
  public final static fz_structure FZ_STRUCTURE_ART = new fz_structure("FZ_STRUCTURE_ART");
  public final static fz_structure FZ_STRUCTURE_SECT = new fz_structure("FZ_STRUCTURE_SECT");
  public final static fz_structure FZ_STRUCTURE_DIV = new fz_structure("FZ_STRUCTURE_DIV");
  public final static fz_structure FZ_STRUCTURE_BLOCKQUOTE = new fz_structure("FZ_STRUCTURE_BLOCKQUOTE");
  public final static fz_structure FZ_STRUCTURE_CAPTION = new fz_structure("FZ_STRUCTURE_CAPTION");
  public final static fz_structure FZ_STRUCTURE_TOC = new fz_structure("FZ_STRUCTURE_TOC");
  public final static fz_structure FZ_STRUCTURE_TOCI = new fz_structure("FZ_STRUCTURE_TOCI");
  public final static fz_structure FZ_STRUCTURE_INDEX = new fz_structure("FZ_STRUCTURE_INDEX");
  public final static fz_structure FZ_STRUCTURE_NONSTRUCT = new fz_structure("FZ_STRUCTURE_NONSTRUCT");
  public final static fz_structure FZ_STRUCTURE_PRIVATE = new fz_structure("FZ_STRUCTURE_PRIVATE");
  public final static fz_structure FZ_STRUCTURE_DOCUMENTFRAGMENT = new fz_structure("FZ_STRUCTURE_DOCUMENTFRAGMENT");
  public final static fz_structure FZ_STRUCTURE_ASIDE = new fz_structure("FZ_STRUCTURE_ASIDE");
  public final static fz_structure FZ_STRUCTURE_TITLE = new fz_structure("FZ_STRUCTURE_TITLE");
  public final static fz_structure FZ_STRUCTURE_FENOTE = new fz_structure("FZ_STRUCTURE_FENOTE");
  public final static fz_structure FZ_STRUCTURE_SUB = new fz_structure("FZ_STRUCTURE_SUB");
  public final static fz_structure FZ_STRUCTURE_P = new fz_structure("FZ_STRUCTURE_P");
  public final static fz_structure FZ_STRUCTURE_H = new fz_structure("FZ_STRUCTURE_H");
  public final static fz_structure FZ_STRUCTURE_H1 = new fz_structure("FZ_STRUCTURE_H1");
  public final static fz_structure FZ_STRUCTURE_H2 = new fz_structure("FZ_STRUCTURE_H2");
  public final static fz_structure FZ_STRUCTURE_H3 = new fz_structure("FZ_STRUCTURE_H3");
  public final static fz_structure FZ_STRUCTURE_H4 = new fz_structure("FZ_STRUCTURE_H4");
  public final static fz_structure FZ_STRUCTURE_H5 = new fz_structure("FZ_STRUCTURE_H5");
  public final static fz_structure FZ_STRUCTURE_H6 = new fz_structure("FZ_STRUCTURE_H6");
  public final static fz_structure FZ_STRUCTURE_LIST = new fz_structure("FZ_STRUCTURE_LIST");
  public final static fz_structure FZ_STRUCTURE_LISTITEM = new fz_structure("FZ_STRUCTURE_LISTITEM");
  public final static fz_structure FZ_STRUCTURE_LABEL = new fz_structure("FZ_STRUCTURE_LABEL");
  public final static fz_structure FZ_STRUCTURE_LISTBODY = new fz_structure("FZ_STRUCTURE_LISTBODY");
  public final static fz_structure FZ_STRUCTURE_TABLE = new fz_structure("FZ_STRUCTURE_TABLE");
  public final static fz_structure FZ_STRUCTURE_TR = new fz_structure("FZ_STRUCTURE_TR");
  public final static fz_structure FZ_STRUCTURE_TH = new fz_structure("FZ_STRUCTURE_TH");
  public final static fz_structure FZ_STRUCTURE_TD = new fz_structure("FZ_STRUCTURE_TD");
  public final static fz_structure FZ_STRUCTURE_THEAD = new fz_structure("FZ_STRUCTURE_THEAD");
  public final static fz_structure FZ_STRUCTURE_TBODY = new fz_structure("FZ_STRUCTURE_TBODY");
  public final static fz_structure FZ_STRUCTURE_TFOOT = new fz_structure("FZ_STRUCTURE_TFOOT");
  public final static fz_structure FZ_STRUCTURE_SPAN = new fz_structure("FZ_STRUCTURE_SPAN");
  public final static fz_structure FZ_STRUCTURE_QUOTE = new fz_structure("FZ_STRUCTURE_QUOTE");
  public final static fz_structure FZ_STRUCTURE_NOTE = new fz_structure("FZ_STRUCTURE_NOTE");
  public final static fz_structure FZ_STRUCTURE_REFERENCE = new fz_structure("FZ_STRUCTURE_REFERENCE");
  public final static fz_structure FZ_STRUCTURE_BIBENTRY = new fz_structure("FZ_STRUCTURE_BIBENTRY");
  public final static fz_structure FZ_STRUCTURE_CODE = new fz_structure("FZ_STRUCTURE_CODE");
  public final static fz_structure FZ_STRUCTURE_LINK = new fz_structure("FZ_STRUCTURE_LINK");
  public final static fz_structure FZ_STRUCTURE_ANNOT = new fz_structure("FZ_STRUCTURE_ANNOT");
  public final static fz_structure FZ_STRUCTURE_EM = new fz_structure("FZ_STRUCTURE_EM");
  public final static fz_structure FZ_STRUCTURE_STRONG = new fz_structure("FZ_STRUCTURE_STRONG");
  public final static fz_structure FZ_STRUCTURE_RUBY = new fz_structure("FZ_STRUCTURE_RUBY");
  public final static fz_structure FZ_STRUCTURE_RB = new fz_structure("FZ_STRUCTURE_RB");
  public final static fz_structure FZ_STRUCTURE_RT = new fz_structure("FZ_STRUCTURE_RT");
  public final static fz_structure FZ_STRUCTURE_RP = new fz_structure("FZ_STRUCTURE_RP");
  public final static fz_structure FZ_STRUCTURE_WARICHU = new fz_structure("FZ_STRUCTURE_WARICHU");
  public final static fz_structure FZ_STRUCTURE_WT = new fz_structure("FZ_STRUCTURE_WT");
  public final static fz_structure FZ_STRUCTURE_WP = new fz_structure("FZ_STRUCTURE_WP");
  public final static fz_structure FZ_STRUCTURE_FIGURE = new fz_structure("FZ_STRUCTURE_FIGURE");
  public final static fz_structure FZ_STRUCTURE_FORMULA = new fz_structure("FZ_STRUCTURE_FORMULA");
  public final static fz_structure FZ_STRUCTURE_FORM = new fz_structure("FZ_STRUCTURE_FORM");
  public final static fz_structure FZ_STRUCTURE_ARTIFACT = new fz_structure("FZ_STRUCTURE_ARTIFACT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static fz_structure swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + fz_structure.class + " with value " + swigValue);
  }

  private fz_structure(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private fz_structure(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private fz_structure(String swigName, fz_structure swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static fz_structure[] swigValues = { FZ_STRUCTURE_INVALID, FZ_STRUCTURE_DOCUMENT, FZ_STRUCTURE_PART, FZ_STRUCTURE_ART, FZ_STRUCTURE_SECT, FZ_STRUCTURE_DIV, FZ_STRUCTURE_BLOCKQUOTE, FZ_STRUCTURE_CAPTION, FZ_STRUCTURE_TOC, FZ_STRUCTURE_TOCI, FZ_STRUCTURE_INDEX, FZ_STRUCTURE_NONSTRUCT, FZ_STRUCTURE_PRIVATE, FZ_STRUCTURE_DOCUMENTFRAGMENT, FZ_STRUCTURE_ASIDE, FZ_STRUCTURE_TITLE, FZ_STRUCTURE_FENOTE, FZ_STRUCTURE_SUB, FZ_STRUCTURE_P, FZ_STRUCTURE_H, FZ_STRUCTURE_H1, FZ_STRUCTURE_H2, FZ_STRUCTURE_H3, FZ_STRUCTURE_H4, FZ_STRUCTURE_H5, FZ_STRUCTURE_H6, FZ_STRUCTURE_LIST, FZ_STRUCTURE_LISTITEM, FZ_STRUCTURE_LABEL, FZ_STRUCTURE_LISTBODY, FZ_STRUCTURE_TABLE, FZ_STRUCTURE_TR, FZ_STRUCTURE_TH, FZ_STRUCTURE_TD, FZ_STRUCTURE_THEAD, FZ_STRUCTURE_TBODY, FZ_STRUCTURE_TFOOT, FZ_STRUCTURE_SPAN, FZ_STRUCTURE_QUOTE, FZ_STRUCTURE_NOTE, FZ_STRUCTURE_REFERENCE, FZ_STRUCTURE_BIBENTRY, FZ_STRUCTURE_CODE, FZ_STRUCTURE_LINK, FZ_STRUCTURE_ANNOT, FZ_STRUCTURE_EM, FZ_STRUCTURE_STRONG, FZ_STRUCTURE_RUBY, FZ_STRUCTURE_RB, FZ_STRUCTURE_RT, FZ_STRUCTURE_RP, FZ_STRUCTURE_WARICHU, FZ_STRUCTURE_WT, FZ_STRUCTURE_WP, FZ_STRUCTURE_FIGURE, FZ_STRUCTURE_FORMULA, FZ_STRUCTURE_FORM, FZ_STRUCTURE_ARTIFACT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

