/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class fz_string {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected fz_string(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(fz_string obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(fz_string obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mupdfJNI.delete_fz_string(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRefs(int value) {
    mupdfJNI.fz_string_refs_set(swigCPtr, this, value);
  }

  public int getRefs() {
    return mupdfJNI.fz_string_refs_get(swigCPtr, this);
  }

  public void setStr(byte[] value) {
    mupdfJNI.fz_string_str_set(swigCPtr, this, value);
  }

  public byte[] getStr() {
    return mupdfJNI.fz_string_str_get(swigCPtr, this);
  }

  public fz_string() {
    this(mupdfJNI.new_fz_string(), true);
  }

}
