/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public interface mupdfConstants {
  public final static byte[] FZ_VERSION = mupdfJNI.FZ_VERSION_get();
  public final static int FZ_VERSION_MAJOR = mupdfJNI.FZ_VERSION_MAJOR_get();
  public final static int FZ_VERSION_MINOR = mupdfJNI.FZ_VERSION_MINOR_get();
  public final static int FZ_VERSION_PATCH = mupdfJNI.FZ_VERSION_PATCH_get();
  public final static int PATH_MAX = mupdfJNI.PATH_MAX_get();
  public final static float FZ_PI = mupdfJNI.FZ_PI_get();
  public final static float FZ_RADIAN = mupdfJNI.FZ_RADIAN_get();
  public final static float FZ_DEGREE = mupdfJNI.FZ_DEGREE_get();
  public final static float FZ_SQRT2 = mupdfJNI.FZ_SQRT2_get();
  public final static float FZ_LN2 = mupdfJNI.FZ_LN2_get();
  public final static int ARCH_HAS_NEON = mupdfJNI.ARCH_HAS_NEON_get();
  public final static int ARCH_HAS_SSE = mupdfJNI.ARCH_HAS_SSE_get();
  public final static int HAVE_SIGSETJMP = mupdfJNI.HAVE_SIGSETJMP_get();
  public final static int EOF = mupdfJNI.EOF_get();
  public final static int SEEK_SET = mupdfJNI.SEEK_SET_get();
  public final static int SEEK_CUR = mupdfJNI.SEEK_CUR_get();
  public final static int SEEK_END = mupdfJNI.SEEK_END_get();
  public final static int FZ_VERBOSE_EXCEPTIONS = mupdfJNI.FZ_VERBOSE_EXCEPTIONS_get();
  public final static int FZ_LOCK_ALLOC = mupdfJNI.FZ_LOCK_ALLOC_get();
  public final static int FZ_LOCK_FREETYPE = mupdfJNI.FZ_LOCK_FREETYPE_get();
  public final static int FZ_LOCK_GLYPHCACHE = mupdfJNI.FZ_LOCK_GLYPHCACHE_get();
  public final static int FZ_LOCK_MAX = mupdfJNI.FZ_LOCK_MAX_get();

  public final static int FZ_STORE_UNLIMITED = mupdfJNI.FZ_STORE_UNLIMITED_get();
  public final static int FZ_STORE_DEFAULT = mupdfJNI.FZ_STORE_DEFAULT_get();

  public final static int FZ_JMPBUF_ALIGN = mupdfJNI.FZ_JMPBUF_ALIGN_get();
  public final static int FZ_LAYOUT_KINDLE_W = mupdfJNI.FZ_LAYOUT_KINDLE_W_get();
  public final static int FZ_LAYOUT_KINDLE_H = mupdfJNI.FZ_LAYOUT_KINDLE_H_get();
  public final static int FZ_LAYOUT_KINDLE_EM = mupdfJNI.FZ_LAYOUT_KINDLE_EM_get();
  public final static int FZ_LAYOUT_US_POCKET_W = mupdfJNI.FZ_LAYOUT_US_POCKET_W_get();
  public final static int FZ_LAYOUT_US_POCKET_H = mupdfJNI.FZ_LAYOUT_US_POCKET_H_get();
  public final static int FZ_LAYOUT_US_POCKET_EM = mupdfJNI.FZ_LAYOUT_US_POCKET_EM_get();
  public final static int FZ_LAYOUT_US_TRADE_W = mupdfJNI.FZ_LAYOUT_US_TRADE_W_get();
  public final static int FZ_LAYOUT_US_TRADE_H = mupdfJNI.FZ_LAYOUT_US_TRADE_H_get();
  public final static int FZ_LAYOUT_US_TRADE_EM = mupdfJNI.FZ_LAYOUT_US_TRADE_EM_get();
  public final static int FZ_LAYOUT_UK_A_FORMAT_W = mupdfJNI.FZ_LAYOUT_UK_A_FORMAT_W_get();
  public final static int FZ_LAYOUT_UK_A_FORMAT_H = mupdfJNI.FZ_LAYOUT_UK_A_FORMAT_H_get();
  public final static int FZ_LAYOUT_UK_A_FORMAT_EM = mupdfJNI.FZ_LAYOUT_UK_A_FORMAT_EM_get();
  public final static int FZ_LAYOUT_UK_B_FORMAT_W = mupdfJNI.FZ_LAYOUT_UK_B_FORMAT_W_get();
  public final static int FZ_LAYOUT_UK_B_FORMAT_H = mupdfJNI.FZ_LAYOUT_UK_B_FORMAT_H_get();
  public final static int FZ_LAYOUT_UK_B_FORMAT_EM = mupdfJNI.FZ_LAYOUT_UK_B_FORMAT_EM_get();
  public final static int FZ_LAYOUT_UK_C_FORMAT_W = mupdfJNI.FZ_LAYOUT_UK_C_FORMAT_W_get();
  public final static int FZ_LAYOUT_UK_C_FORMAT_H = mupdfJNI.FZ_LAYOUT_UK_C_FORMAT_H_get();
  public final static int FZ_LAYOUT_UK_C_FORMAT_EM = mupdfJNI.FZ_LAYOUT_UK_C_FORMAT_EM_get();
  public final static int FZ_LAYOUT_A5_W = mupdfJNI.FZ_LAYOUT_A5_W_get();
  public final static int FZ_LAYOUT_A5_H = mupdfJNI.FZ_LAYOUT_A5_H_get();
  public final static int FZ_LAYOUT_A5_EM = mupdfJNI.FZ_LAYOUT_A5_EM_get();
  public final static int FZ_DEFAULT_LAYOUT_W = mupdfJNI.FZ_DEFAULT_LAYOUT_W_get();
  public final static int FZ_DEFAULT_LAYOUT_H = mupdfJNI.FZ_DEFAULT_LAYOUT_H_get();
  public final static int FZ_DEFAULT_LAYOUT_EM = mupdfJNI.FZ_DEFAULT_LAYOUT_EM_get();

  public final static byte[] FZ_META_FORMAT = mupdfJNI.FZ_META_FORMAT_get();
  public final static byte[] FZ_META_ENCRYPTION = mupdfJNI.FZ_META_ENCRYPTION_get();
  public final static byte[] FZ_META_INFO = mupdfJNI.FZ_META_INFO_get();
  public final static byte[] FZ_META_INFO_TITLE = mupdfJNI.FZ_META_INFO_TITLE_get();
  public final static byte[] FZ_META_INFO_AUTHOR = mupdfJNI.FZ_META_INFO_AUTHOR_get();
  public final static byte[] FZ_META_INFO_SUBJECT = mupdfJNI.FZ_META_INFO_SUBJECT_get();
  public final static byte[] FZ_META_INFO_KEYWORDS = mupdfJNI.FZ_META_INFO_KEYWORDS_get();
  public final static byte[] FZ_META_INFO_CREATOR = mupdfJNI.FZ_META_INFO_CREATOR_get();
  public final static byte[] FZ_META_INFO_PRODUCER = mupdfJNI.FZ_META_INFO_PRODUCER_get();
  public final static byte[] FZ_META_INFO_CREATIONDATE = mupdfJNI.FZ_META_INFO_CREATIONDATE_get();
  public final static byte[] FZ_META_INFO_MODIFICATIONDATE = mupdfJNI.FZ_META_INFO_MODIFICATIONDATE_get();
  public final static double M_PI = mupdfJNI.M_PI_get();
  public final static int FZ_RI_PERCEPTUAL = mupdfJNI.FZ_RI_PERCEPTUAL_get();
  public final static int FZ_RI_RELATIVE_COLORIMETRIC = mupdfJNI.FZ_RI_RELATIVE_COLORIMETRIC_get();
  public final static int FZ_RI_SATURATION = mupdfJNI.FZ_RI_SATURATION_get();
  public final static int FZ_RI_ABSOLUTE_COLORIMETRIC = mupdfJNI.FZ_RI_ABSOLUTE_COLORIMETRIC_get();

  public final static int FZ_MAX_COLORS = mupdfJNI.FZ_MAX_COLORS_get();

  public final static int FZ_COLORSPACE_IS_DEVICE = mupdfJNI.FZ_COLORSPACE_IS_DEVICE_get();
  public final static int FZ_COLORSPACE_IS_ICC = mupdfJNI.FZ_COLORSPACE_IS_ICC_get();
  public final static int FZ_COLORSPACE_HAS_CMYK = mupdfJNI.FZ_COLORSPACE_HAS_CMYK_get();
  public final static int FZ_COLORSPACE_HAS_SPOTS = mupdfJNI.FZ_COLORSPACE_HAS_SPOTS_get();
  public final static int FZ_COLORSPACE_HAS_CMYK_AND_SPOTS = mupdfJNI.FZ_COLORSPACE_HAS_CMYK_AND_SPOTS_get();

  public final static int FZ_PIXMAP_FLAG_INTERPOLATE = mupdfJNI.FZ_PIXMAP_FLAG_INTERPOLATE_get();
  public final static int FZ_PIXMAP_FLAG_FREE_SAMPLES = mupdfJNI.FZ_PIXMAP_FLAG_FREE_SAMPLES_get();

  public final static int FZ_DEVFLAG_MASK = mupdfJNI.FZ_DEVFLAG_MASK_get();
  public final static int FZ_DEVFLAG_COLOR = mupdfJNI.FZ_DEVFLAG_COLOR_get();
  public final static int FZ_DEVFLAG_UNCACHEABLE = mupdfJNI.FZ_DEVFLAG_UNCACHEABLE_get();
  public final static int FZ_DEVFLAG_FILLCOLOR_UNDEFINED = mupdfJNI.FZ_DEVFLAG_FILLCOLOR_UNDEFINED_get();
  public final static int FZ_DEVFLAG_STROKECOLOR_UNDEFINED = mupdfJNI.FZ_DEVFLAG_STROKECOLOR_UNDEFINED_get();
  public final static int FZ_DEVFLAG_STARTCAP_UNDEFINED = mupdfJNI.FZ_DEVFLAG_STARTCAP_UNDEFINED_get();
  public final static int FZ_DEVFLAG_DASHCAP_UNDEFINED = mupdfJNI.FZ_DEVFLAG_DASHCAP_UNDEFINED_get();
  public final static int FZ_DEVFLAG_ENDCAP_UNDEFINED = mupdfJNI.FZ_DEVFLAG_ENDCAP_UNDEFINED_get();
  public final static int FZ_DEVFLAG_LINEJOIN_UNDEFINED = mupdfJNI.FZ_DEVFLAG_LINEJOIN_UNDEFINED_get();
  public final static int FZ_DEVFLAG_MITERLIMIT_UNDEFINED = mupdfJNI.FZ_DEVFLAG_MITERLIMIT_UNDEFINED_get();
  public final static int FZ_DEVFLAG_LINEWIDTH_UNDEFINED = mupdfJNI.FZ_DEVFLAG_LINEWIDTH_UNDEFINED_get();
  public final static int FZ_DEVFLAG_BBOX_DEFINED = mupdfJNI.FZ_DEVFLAG_BBOX_DEFINED_get();
  public final static int FZ_DEVFLAG_GRIDFIT_AS_TILED = mupdfJNI.FZ_DEVFLAG_GRIDFIT_AS_TILED_get();

  public final static int FZ_BLEND_NORMAL = mupdfJNI.FZ_BLEND_NORMAL_get();
  public final static int FZ_BLEND_MULTIPLY = mupdfJNI.FZ_BLEND_MULTIPLY_get();
  public final static int FZ_BLEND_SCREEN = mupdfJNI.FZ_BLEND_SCREEN_get();
  public final static int FZ_BLEND_OVERLAY = mupdfJNI.FZ_BLEND_OVERLAY_get();
  public final static int FZ_BLEND_DARKEN = mupdfJNI.FZ_BLEND_DARKEN_get();
  public final static int FZ_BLEND_LIGHTEN = mupdfJNI.FZ_BLEND_LIGHTEN_get();
  public final static int FZ_BLEND_COLOR_DODGE = mupdfJNI.FZ_BLEND_COLOR_DODGE_get();
  public final static int FZ_BLEND_COLOR_BURN = mupdfJNI.FZ_BLEND_COLOR_BURN_get();
  public final static int FZ_BLEND_HARD_LIGHT = mupdfJNI.FZ_BLEND_HARD_LIGHT_get();
  public final static int FZ_BLEND_SOFT_LIGHT = mupdfJNI.FZ_BLEND_SOFT_LIGHT_get();
  public final static int FZ_BLEND_DIFFERENCE = mupdfJNI.FZ_BLEND_DIFFERENCE_get();
  public final static int FZ_BLEND_EXCLUSION = mupdfJNI.FZ_BLEND_EXCLUSION_get();
  public final static int FZ_BLEND_HUE = mupdfJNI.FZ_BLEND_HUE_get();
  public final static int FZ_BLEND_SATURATION = mupdfJNI.FZ_BLEND_SATURATION_get();
  public final static int FZ_BLEND_COLOR = mupdfJNI.FZ_BLEND_COLOR_get();
  public final static int FZ_BLEND_LUMINOSITY = mupdfJNI.FZ_BLEND_LUMINOSITY_get();
  public final static int FZ_BLEND_MODEMASK = mupdfJNI.FZ_BLEND_MODEMASK_get();
  public final static int FZ_BLEND_ISOLATED = mupdfJNI.FZ_BLEND_ISOLATED_get();
  public final static int FZ_BLEND_KNOCKOUT = mupdfJNI.FZ_BLEND_KNOCKOUT_get();

  public final static int FZ_FUNCTION_MAX_N = mupdfJNI.FZ_FUNCTION_MAX_N_get();
  public final static int FZ_FUNCTION_MAX_M = mupdfJNI.FZ_FUNCTION_MAX_M_get();

  public final static int fz_device_container_stack_is_clip = mupdfJNI.fz_device_container_stack_is_clip_get();
  public final static int fz_device_container_stack_is_mask = mupdfJNI.fz_device_container_stack_is_mask_get();
  public final static int fz_device_container_stack_is_group = mupdfJNI.fz_device_container_stack_is_group_get();
  public final static int fz_device_container_stack_is_tile = mupdfJNI.fz_device_container_stack_is_tile_get();

  public final static int FZ_DONT_INTERPOLATE_IMAGES = mupdfJNI.FZ_DONT_INTERPOLATE_IMAGES_get();
  public final static int FZ_NO_CACHE = mupdfJNI.FZ_NO_CACHE_get();
  public final static int FZ_DONT_DECODE_IMAGES = mupdfJNI.FZ_DONT_DECODE_IMAGES_get();

  public final static int FZ_TEST_OPT_IMAGES = mupdfJNI.FZ_TEST_OPT_IMAGES_get();
  public final static int FZ_TEST_OPT_SHADINGS = mupdfJNI.FZ_TEST_OPT_SHADINGS_get();

}
