/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_transition_p_float__p_fz_transition {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_transition_p_float__p_fz_transition(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_transition_p_float__p_fz_transition() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_transition_p_float__p_fz_transition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_f_p_struct_fz_context_p_struct_fz_page_p_fz_transition_p_float__p_fz_transition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

