/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mobi.librera.mupdf;


public class SWIGTYPE_p_f_p_struct_fz_context_p_void_p_q_const__float_int_p_float_int__void {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_struct_fz_context_p_void_p_q_const__float_int_p_float_int__void(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_struct_fz_context_p_void_p_q_const__float_int_p_float_int__void() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_struct_fz_context_p_void_p_q_const__float_int_p_float_int__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_f_p_struct_fz_context_p_void_p_q_const__float_int_p_float_int__void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

